import {
  SiGo,
  SiPython,
  SiFastapi,
  SiLangchain,
  SiDocker,
  SiKubernetes,
  SiPostgresql,
  SiMongodb,
  SiRedis,
  SiGit,
  SiGithub,
  SiLinux,
  SiJavascript,
  SiTypescript,
  SiReact,
  SiNextdotjs,
} from "react-icons/si";

export const skillsData = [
  {
    title: "Go",
    level: "Advanced",
    icon: SiGo,
    color: "#00ADD8",
  },
  {
    title: "Python",
    level: "Advanced",
    icon: SiPython,
    color: "#FFD43B",
  },
  {
    title: "FastAPI",
    level: "Advanced",
    icon: SiFastapi,
    color: "#00C7B7",
  },
  {
    title: "LangChain",
    level: "Advanced",
    icon: SiLangchain,
    color: "#00E676",
  },
  {
    title: "Docker",
    level: "Advanced",
    icon: SiDocker,
    color: "#2496ED",
  },
  {
    title: "Kubernetes",
    level: "Advanced",
    icon: SiKubernetes,
    color: "#326CE5",
  },
  {
    title: "PostgreSQL",
    level: "Advanced",
    icon: SiPostgresql,
    color: "#336791",
  },
  {
    title: "MongoDB",
    level: "Advanced",
    icon: SiMongodb,
    color: "#47A248",
  },
  {
    title: "Redis",
    level: "Intermediate",
    icon: SiRedis,
    color: "#DC382D",
  },
  {
    title: "Git",
    level: "Advanced",
    icon: SiGit,
    color: "#F05032",
  },
  {
    title: "GitHub",
    level: "Advanced",
    icon: SiGithub,
    color: "#FFFFFF",
  },
  {
    title: "Linux",
    level: "Advanced",
    icon: SiLinux,
    color: "#FCC624",
  },
  {
    title: "JavaScript",
    level: "Advanced",
    icon: SiJavascript,
    color: "#F7DF1E",
  },
  {
    title: "TypeScript",
    level: "Advanced",
    icon: SiTypescript,
    color: "#3178C6",
  },
  {
    title: "React",
    level: "Intermediate",
    icon: SiReact,
    color: "#61DAFB",
  },
  {
    title: "Next.js",
    level: "Intermediate",
    icon: SiNextdotjs,
    color: "#FFFFFF",
  },
];